apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ecommerce-benign
  labels:
    pfe.io/purpose: ecommerce
    pfe.io/zone: benign
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pfe-hostpath
  hostPath:
    path: /srv/pfe-lab/ecommerce
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ecommerce-attack
  labels:
    pfe.io/purpose: ecommerce
    pfe.io/zone: attack
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pfe-hostpath
  hostPath:
    path: /srv/pfe-lab/ecommerce
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fio
  labels:
    pfe.io/purpose: fio
    pfe.io/zone: benign
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pfe-hostpath
  hostPath:
    path: /srv/pfe-lab/fio
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filebench
  labels:
    pfe.io/purpose: filebench
    pfe.io/zone: benign
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pfe-hostpath
  hostPath:
    path: /srv/pfe-lab/filebench
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-benign
  labels:
    pfe.io/purpose: shared
    pfe.io/zone: benign
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pfe-hostpath
  hostPath:
    path: /srv/pfe-lab/shared
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-attack
  labels:
    pfe.io/purpose: shared
    pfe.io/zone: attack
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pfe-hostpath
  hostPath:
    path: /srv/pfe-lab/shared
    type: DirectoryOrCreate
