apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-workload-config
  namespace: benign-lab
  labels:
    app: fio-workload
    pfe.io/workload: benign-io
data:
  fio-job.ini: |
    [global]
    directory=/data/fio
    ioengine=sync
    direct=0
    time_based
    runtime=30
    size=64m
    bs=4k
    group_reporting
    randrepeat=1
    stonewall

    [benign-randread]
    rw=randread
    numjobs=1

    [benign-randwrite]
    rw=randwrite
    numjobs=1
