apiVersion: v1
kind: Namespace
metadata:
  name: benign-lab
  labels:
    pfe.io/zone: benign
---
apiVersion: v1
kind: Namespace
metadata:
  name: attack-lab
  labels:
    pfe.io/zone: attack
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    pfe.io/zone: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pfe.io/zone: monitoring
